import { IStaticKnowbookDefinition } from "./globals";

export const staticKnowbooks: IStaticKnowbookDefinition[] = [
  { nameOrPeriod: "2016-2020", lang: "" },
  // { nameOrPeriod: "2021", lang: "" },
  {
    nameOrPeriod: "Ecologie_Developpement_Durable",
    display: "Ecologie et Développement Durable",
    lang: "fr",
    items: [
      "Tableau périodique des éléments",
      "Classification scientifique des espèces",
      "Extinction des espèces",
      "Grand requin blanc",
      "Développement durable",
      "Homo sapiens",
      "Perte de la biodiversité",
      "Ressources et consommation énergétiques mondiales",
      "Croissance économique",
      "Orque",
      "Les Limites à la croissance",
      "Jean-Marc Jancovici",
      "Environnement",
      "Biodiversité",
      "Énergie (économie)",
      "Greta Thunberg",
      "Objectifs de développement durable",
      "Pandémie de Covid-19",
      "Protection de l'environnement",
      "SARS-CoV",
    ],
  },
  {
    nameOrPeriod: "Infinis",
    lang: "fr",
    items: [
      "Physique quantique",
      "Relativité générale",
      "Calculateur quantique",
      "Infini",
      "Intrication quantique",
      "Voie lactée",
      "Exoplanète",
      "Système solaire",
      "Trou noir",
      "Matière noire",
    ],
  },
  {
    nameOrPeriod: "Philosophie",
    lang: "fr",
    items: [
      "William James",
      "Blaise Pascal",
      "Marc Aurèle",
      "Sénèque",
      "Albert Camus",
      "Baruch Spinoza",
      "Arthur Schopenhauer",
      "Henri Bergson",
      "Épicure",
      "Stoïcisme",
      "Philosophe",
      "Jean-Jacques Rousseau",
      "Platon",
      "Aristote",
      "Karl Marx",
      "Voltaire",
      "Socrate",
      "René Descartes",
      "Georg Wilhelm Friedrich Hegel",
      "Emmanuel Kant",
      "Friedrich Nietzsche",
      "Jean-Paul Sartre",
      "Adam Smith",
      "Épistémologie",
    ],
  },
];
