import { ConfigLanguage, IStaticKnowbookDefinition } from "./globals";

export const staticKnowbooks: IStaticKnowbookDefinition[] = [
  { nameOrPeriod: "2016-2020", lang: "" },
  { nameOrPeriod: "2021", lang: "" },
  {
    nameOrPeriod: "Ecologie_Developpement_Durable",
    display: "Ecologie et Développement Durable",
    lang: ConfigLanguage.fr,
    items: [
      "Classification scientifique des espèces",
      "Extinction des espèces",
      "Grand requin blanc",
      "Développement durable",
      "Homo sapiens",
      "Ressources et consommation énergétiques mondiales",
      "Orque",
      "Les Limites à la croissance",
      "Jean-Marc Jancovici",
      "Environnement",
      "Biodiversité",
      "Énergie (économie)",
      "Greta Thunberg",
      "Objectifs de développement durable",
      "Pandémie de Covid-19",
    ],
  },
  {
    nameOrPeriod: "Infinis",
    lang: ConfigLanguage.fr,
    items: [
      "Physique quantique",
      "Relativité générale",
      "Calculateur quantique",
      "Infini",
      "Intrication quantique",
      "Voie lactée",
      "Exoplanète",
      "Système solaire",
      "Trou noir",
    ],
  },
  {
    nameOrPeriod: "Philosophie",
    lang: ConfigLanguage.fr,
    items: [
      "William James",
      "Blaise Pascal",
      "Marc Aurèle",
      "Sénèque",
      "Albert Camus",
      "Baruch Spinoza",
      "Arthur Schopenhauer",
      "Henri Bergson",
      "Épicure",
      "Stoïcisme",
      "Philosophe",
      "Jean-Jacques Rousseau",
      "Platon",
      "Aristote",
      "Karl Marx",
      "Voltaire",
      "Socrate",
      "René Descartes",
      "Georg Wilhelm Friedrich Hegel",
      "Emmanuel Kant",
      "Friedrich Nietzsche",
      "Jean-Paul Sartre",
      "Adam Smith",
      "Épistémologie",
      "Alchimie",
    ],
  },
  {
    nameOrPeriod: "Ecologia",
    lang: ConfigLanguage.it,
    items: [
      "Ecologia",
      "Sviluppo sostenibile",
      "Rapporto sui limiti dello sviluppo",
      "Biodiversità",
      "Greta Thunberg",
      "Obiettivi di sviluppo sostenibile",
      "COVID-19",
    ],
  },
  {
    nameOrPeriod: "Infinito",
    lang: ConfigLanguage.it,
    items: [
      "Meccanica quantistica",
      "Relatività generale",
      "Infinito (matematica)",
      "Via Lattea",
      "Pianeta extrasolare",
      "Sistema solare",
      "Buco nero",
    ],
  },
  {
    nameOrPeriod: "Ecology",
    lang: ConfigLanguage.en,
    items: [
      "Ecology",
      "Sustainable development",
      "The Limits to Growth",
      "Biodiversity",
      "Greta Thunberg",
      "Sustainable Development Goals",
      "COVID-19",
    ],
  },
  {
    nameOrPeriod: "Infinity",
    lang: ConfigLanguage.en,
    items: [
      "Quantum mechanics",
      "General relativity",
      "Milky Way",
      "Exoplanet",
      "Solar System",
      "Black hole",
    ],
  },
];
