export const configDataMobile = {
  // max_nodes_network: 50, //Only Network
  amount_bestPublicKnowbooks: 11,
  layout: {
    heightUser: "80vh", //600,
    heightChangePassword: "45vh",
    heightHeader: 60, //7%
    heightBody: "90vh", //87%
    heightBottom: "0vh",
  },
  rounding_menu: 3,
  rounding_form: 6,
  rounding_item: 6,
  rounding_knowbooks: "circle",
  size_icon_generic: "sm",
  size_icon_menu_navigation: "xl",
  size_icon_card: "xs",
  size_icon_card_type: 12,
  size_text_generic: "100",
  size_text_header: "300",
  size_button_generic: "md",
  size_factor_atom_network: 0.5,
  size_factor_knowbook_network: 0.5,
  dialogs: {
    field_text_size: "md",
    item_checkbox_size: "md",
  },
  atom_sizes: {
    height: 155,
    width: 155,
    image_ratio: "75%",
    // lgColumn: 4,
    // mdColumn: 4,
    // smColumn: 6,
    // column: 6,
    lgPadding: 2,
    mdPadding: 2,
    smPadding: 2,
    padding: 2,
    size_text_title: "100",
  },
  knowbook_sizes: {
    height: 160, //130,
    width: 160, //130,
    image_ratio: "75%",
    // lgColumn: 4,
    // mdColumn: 4,
    // smColumn: 6,
    // column: 6,
    lgPadding: 1,
    mdPadding: 1,
    smPadding: 1,
    padding: 1,
    size_text_title: "100",
  },
};
