export const configDataMobile = {
  // display: {
  //   displayFeedIncrement: 1, //10,
  //   amount_related_displayed: 32,
  // },
  // max_nodes_network: 50, //Only Network
  // heightTopAndBottom: 200, //Only Network

  rounding_menu: 3,
  rounding_item: 6,
  rounding_item_viz: 4,
  rounding_knowbooks: "circle",
  size_icon_menu: "lg",
  size_icon_menu_article: "xs",
  size_icon_card: "xs",
  header_title_size: "300",
  layout: {
    heightUser: "80vh", //600,
    heightChangePassword: "45vh",
    heightHeader: 60, //7%
    heightBody: "90vh", //87%
    heightBottom: "0vh",
    // heightSlideArticle: "67vh",
    SVG_R_Max: 800,
    SVG_R_Ratio: 1.2, //0.8,
    SVG_deltaStepGrid_Ratio: 1.05,
    SVG_Slider_Circle_Ratio: 1.2,
    SVG_Slider_Grid_Ratio: 1.0,
    SVG_Element_Circle_Density: 0.6,
    SVG_Root_Ratio: 0.8,
    fontsize: "12",
    card_size_factor: 0.6,
  },
  dialogs: {
    title_size: "300",
    texfield_size: "md",
    item_checkbox_size: "md",
    button_icon_size: "lg",
  },
  dropdown: {
    width: 130,
    height: 50,
    delta_position: { x: -30, y: -20 },
  },
  atom_sizes: {
    height: 155,
    width: 155,
    image_ratio: "75%",
    // lgColumn: 4,
    // mdColumn: 4,
    // smColumn: 6,
    // column: 6,
    lgPadding: 2,
    mdPadding: 2,
    smPadding: 2,
    padding: 2,
    title_card_size: "100",
    max_title_size: 30,
  },
  knowbook_sizes: {
    height: 160, //130,
    width: 160, //130,
    image_ratio: "75%",
    // lgColumn: 4,
    // mdColumn: 4,
    // smColumn: 6,
    // column: 6,
    lgPadding: 1,
    mdPadding: 1,
    smPadding: 1,
    padding: 1,
    title_card_size: "100",
    max_title_size: 25,
  },
  About: {
    ratio_presentation: "65vh",
    ratio_image: "80%",
  },
  atom_compact_vizs_sizes: {
    height: 80,
    width: 80,
    lgPadding: 2,
    mdPadding: 2,
    smPadding: 1,
    padding: 1,
    title_card_size: "100",
    max_title_size: 20,
  },
};
