const card_compact_vizs_size = 70;

export const configDataMobile = {
  display: {
    displayFeedIncrement: 10,
    amount_related_displayed: 32,
  },
  max_nodes_network: 50, //Only Network
  heightTopAndBottom: 200, //Only Network
  heightUser: 500,
  heightChangePassword: "45vh",
  rounding_menu: 4,
  rounding_item: 6,
  rounding_knowbooks: "circle",
  size_icon_menu: "lg",
  size_icon_card: "xs",
  header_title_size: "sm",
  layout: {
    heightHeader: 60, //7%
    heightBody: "90vh", //87%
    heightBottom: "0vh",
    SVG_R_Max: 800,
    SVG_R_Ratio: 1.2, //0.8,
    SVG_deltaStepGrid_Ratio: 1.05,
    SVG_Slider_Circle_Ratio: 1.2,
    SVG_Slider_Grid_Ratio: 1.0,
    SVG_Element_Circle_Density: 0.6,
    SVG_Root_Ratio: 0.8,
    fontsize: "12",
    ratio_H_W_Item: 1.33,
  },
  dialogs: {
    title_size: "lg",
    texfield_size: "md",
    item_size: "md",
    button_icon_size: "lg",
  },
  dropdown: {
    width: 130,
    height: 50,
    delta_position: { x: -30, y: -20 },
  },
  atom_sizes: {
    height: 120,
    image_ratio: "75%",
    lgColumn: 4,
    mdColumn: 4,
    smColumn: 6,
    column: 6,
    lgPadding: 2,
    mdPadding: 2,
    smPadding: 2,
    padding: 2,
    title_card_size: "sm",
    max_title_size: 15,
  },
  knowbook_sizes: {
    height: 120,
    image_ratio: "75%",
    lgColumn: 4,
    mdColumn: 4,
    smColumn: 6,
    column: 6,
    lgPadding: 1,
    mdPadding: 1,
    smPadding: 1,
    padding: 1,
    title_card_size: "sm",
    max_title_size: 20,
  },
  About: {
    ratio_presentation: "65vh",
    ratio_image: "80%",
  },
  atom_compact_vizs_sizes: {
    height: card_compact_vizs_size,
    width: card_compact_vizs_size,
    lgPadding: 2,
    mdPadding: 2,
    smPadding: 1,
    padding: 1,
    title_card_size: "sm",
    max_title_size: 20,
  },
};
