export const paths = {
  item_empty_image: "/The_Scientific_Universe_small.webp",
  knowbook_all_image: "/500px-Book_closed_template_small.svg.webp",
  knowbook_none_image: "/The_Scientific_Universe_small.webp",
  // knowbook_image: "",
  // user_image: "/icon_user.jpg",
  // image_logo_W: "/logo2_W.webp",
  image_logo_B: "/logo2_B.webp",
  image_logo_W_small: "/logo2_W_small.webp",
  // image_logo_B_small: "/logo2_B_small.webp",
  image_landing: "/landing.webp",
  image_install: "/install.webp",
  pages: {
    Landing: "/Landing",
    Home: "/Home",
    Knowbooks: "/Knowbooks",
    Knowbook: "/Knowbook",
    KnowbookSaved: "/KnowbookSpecialSaved",
    KnowbookNone: "/KnowbookSpecialNone",
    ItemArticle: "/ItemArticle",
    ItemNetwork: "/ItemNetwork",
    User: "/User",
    ChangePassword: "/ChangePassword",
    empty: "",
  },
  // landing: {
  //   // image_background: "/background_4_large.jpg",
  //   // image_background: "/Polygon Luminary 0.svg",
  //   images_feature: ["/capture11.png", "/capture21.png", "/capture3.png"],
  // },
};
