export const displayMobile = {
  //card_height: 250,
  amount_item_displayed: 100,
  max_nodes_network: 5,
  // min_width_network: 500,
  heightTopAndBottom: 180,
  rounding_menu: 6,
  rounding_item: 4,
  size_icon_menu: "md",
  size_icon_card: "xs",
  title_card_size: "sm",
  header_size: "sm",
  dialogs: {
    title_size: "lg",
    texfield_size: "md",
    item_size: "md",
    button_icon_size: "sm",
  },
  atom_sizes: {
    height: 250,
    image_ratio: "75%",
    lgColumn: 2,
    mdColumn: 3,
    smColumn: 4,
    column: 6,
    lgPadding: 6,
    mdPadding: 6,
    smPadding: 2,
    padding: 2,
    max_title_size: 33,
  },
  atom_compact_sizes: {
    height: 120,
    width: 120,
    lgPadding: 2,
    mdPadding: 2,
    smPadding: 1,
    padding: 1,
    max_title_size: 33,
  },
  atom_compact_vizs_sizes: {
    height: 100,
    width: 100,
    lgPadding: 2,
    mdPadding: 2,
    smPadding: 1,
    padding: 1,
    max_title_size: 33,
  },
  knowbook_sizes: {
    height: 120,
    image_ratio: "75%",
    lgColumn: 3,
    mdColumn: 3,
    smColumn: 3,
    column: 3,
    lgPadding: 2,
    mdPadding: 2,
    smPadding: 2,
    padding: 2,
    max_title_size: 33,
  },
  knowbook_compact_sizes: {
    height: 120,
    width: 120,
    // image_ratio: "80%",
    lgPadding: 2,
    mdPadding: 2,
    smPadding: 1,
    padding: 1,
    max_title_size: 33,
  },
  landing: {
    sizes: {
      height: 300,
      image_ratio: "77%",
      lgColumn: 6,
      mdColumn: 6,
      smColumn: 6,
      column: 6,
      lgPadding: 5,
      mdPadding: 5,
      smPadding: 2,
      padding: 2,
      max_title_size: 99,
    },
    ratio_main: "75vh",
    ratio_image: "30vh",
    header_size: "lg",
    size_icon_card: "lg",
    // features_color: ["red", "green", "red", "green"],
  },
};
