export const displayDesktop = {
  //card_height: 250,
  amount_item_displayed: 100,
  max_nodes_network: 110,
  // min_width_network: 500,
  amount_card_compact_width: 3,
  deltaScreenViewport: 280,
  size_icon_menu: "sm",
  size_icon_card: "xs",
  title_card_size: "md",
  header_size: "md",
  dialogs: {
    title_size: "lg",
    texfield_size: "lg",
    item_size: "md",
    button_icon_size: "md",
  },
  colors: {
    //https://www.rapidtables.com/web/color/RGB_Color.html
    background: "white",
    menu: "white",
    headers: "white",
    item_color: "white",
    knowbook_color: "white",
    item_color_image: "rgb(220, 220, 220)",
    knowbook_color_image: "rgb(245, 245, 245)",
  },
  atom_sizes: {
    height: 250,
    image_ratio: "75%",
    lgColumn: 2,
    mdColumn: 3,
    smColumn: 4,
    column: 6,
    lgPadding: 6,
    mdPadding: 6,
    smPadding: 2,
    padding: 2,
    max_title_size: 33,
  },
  atom_compact_sizes: {
    height: 150,
    width: 150,
    // image_ratio: "80%",
    lgPadding: 2,
    mdPadding: 2,
    smPadding: 2,
    padding: 2,
    max_title_size: 33,
  },
  knowbook_sizes: {
    height: 180,
    image_ratio: "75%",
    lgColumn: 2,
    mdColumn: 2,
    smColumn: 3,
    column: 3,
    lgPadding: 2,
    mdPadding: 2,
    smPadding: 2,
    padding: 2,
    max_title_size: 33,
  },
  knowbook_compact_sizes: {
    height: 150,
    width: 150,
    // image_ratio: "80%",
    lgPadding: 2,
    mdPadding: 2,
    smPadding: 2,
    padding: 2,
    max_title_size: 33,
  },
};
