import { GUI_CONFIG_display_T } from "./types";

export const displayDesktop: GUI_CONFIG_display_T = {
  //card_height: 250,
  amount_item_displayed: 200,
  max_nodes_network: 110,
  // min_width_network: 500,
  heightTopAndBottom: 200,
  rounding_menu: 6,
  rounding_item: 4,
  size_icon_menu: "sm",
  size_icon_card: "xs",
  title_card_size: "sm",
  header_size: "md",
  dialogs: {
    title_size: "lg",
    texfield_size: "lg",
    item_size: "md",
    button_icon_size: "md",
  },
  atom_sizes: {
    height: 250,
    image_ratio: "75%",
    lgColumn: 2,
    mdColumn: 3,
    smColumn: 4,
    column: 6,
    lgPadding: 6,
    mdPadding: 6,
    smPadding: 2,
    padding: 2,
    max_title_size: 33,
  },
  atom_compact_sizes: {
    height: 150,
    width: 150,
    lgPadding: 2,
    mdPadding: 2,
    smPadding: 2,
    padding: 2,
    max_title_size: 33,
  },
  atom_compact_vizs_sizes: {
    height: 120,
    width: 120,
    lgPadding: 2,
    mdPadding: 2,
    smPadding: 1,
    padding: 1,
    max_title_size: 33,
  },
  knowbook_sizes: {
    height: 180,
    image_ratio: "75%",
    lgColumn: 2,
    mdColumn: 3,
    smColumn: 4,
    column: 6,
    lgPadding: 6,
    mdPadding: 6,
    smPadding: 2,
    padding: 2,
    max_title_size: 33,
  },
  knowbook_compact_sizes: {
    height: 150,
    width: 150,
    // image_ratio: "80%",
    lgPadding: 2,
    mdPadding: 2,
    smPadding: 2,
    padding: 2,
    max_title_size: 33,
  },
  landing: {
    sizes: {
      height: 300,
      image_ratio: "75%",
      lgColumn: 3,
      mdColumn: 3,
      smColumn: 6,
      column: 6,
      lgPadding: 2,
      mdPadding: 2,
      smPadding: 2,
      padding: 2,
      max_title_size: 99,
    },
    ratio_main: "50vh",
    ratio_image: "20vh",
    header_size: "lg",
    size_icon_card: "xl",
    // features_color: ["red", "green", "red", "green"],
  },
};
