export const paths = {
  item_empty_image: "/The_Scientific_Universe_small.png",
  knowbook_all_image: "/500px-Book_closed_template_small.svg.png",
  knowbook_none_image: "/The_Scientific_Universe_small.png",
  // knowbook_image: "",
  user_image: "/icon_user.jpg",
  image_logo_W: "/logo2_W.png",
  image_logo_B: "/logo2_B.png",
  image_landing: "/landing.png",
  pages: {
    Landing: "/Landing",
    Home: "/Home",
    Knowbooks: "/Knowbooks",
    Knowbook: "/Knowbook",
    KnowbookSaved: "/KnowbookSpecialSaved",
    KnowbookNone: "/KnowbookSpecialNone",
    Item: "/ItemView",
    User: "/User",
    empty: "",
  },
  // landing: {
  //   // image_background: "/background_4_large.jpg",
  //   // image_background: "/Polygon Luminary 0.svg",
  //   images_feature: ["/capture11.png", "/capture21.png", "/capture3.png"],
  // },
};
